### ISSUE TITLE
Implement `num_traits::NumAssignOps`

### ISSUE THREAD

**Issue by pierwill** [pierwill/gaussiant#18]
This is probably a good idea.

See [`num_traits::NumAssignOps`](https://docs.rs/num-traits/latest/num_traits/trait.NumAssignOps.html).

## TODOs

- [x] [`AddAssign`](https://doc.rust-lang.org/nightly/core/ops/arith/trait.AddAssign.html)
- [x] [`SubAssign`](https://doc.rust-lang.org/nightly/core/ops/arith/trait.SubAssign.html)
- [x] [`MulAssign`](https://doc.rust-lang.org/nightly/core/ops/arith/trait.MulAssign.html)
- [x] [`DivAssign`](https://doc.rust-lang.org/nightly/core/ops/arith/trait.DivAssign.html)
- [x] [`RemAssign`](https://doc.rust-lang.org/nightly/core/ops/arith/trait.RemAssign.html)
